# @package _global_
defaults:
  - /reproduction/b20_qwen35_2b_5090
  - _self_

reproduction:
  adapter_export_dir: /root/autodl-tmp/rememr1/profiles/rtx5090-32g-qwen35-2b-v1/outputs/${reproduction.offload_profile}/b40/artifacts/adapter

actor_rollout_ref:
  actor:
    optim:
      total_training_steps: 40

critic:
  optim:
    total_training_steps: 40

trainer:
  total_training_steps: 40
  experiment_name: qwen35-2b-5090-B-${reproduction.offload_profile}-seed42-b40
  rollout_data_dir: /root/autodl-tmp/rememr1/profiles/rtx5090-32g-qwen35-2b-v1/outputs/${reproduction.offload_profile}/b40/logs/rollouts
  validation_data_dir: /root/autodl-tmp/rememr1/profiles/rtx5090-32g-qwen35-2b-v1/outputs/${reproduction.offload_profile}/b40/logs/validation
  resume_mode: resume_path
  resume_from_path: /root/autodl-tmp/rememr1/profiles/rtx5090-32g-qwen35-2b-v1/outputs/${reproduction.offload_profile}/b20/checkpoints/global_step_20
  default_local_dir: /root/autodl-tmp/rememr1/profiles/rtx5090-32g-qwen35-2b-v1/outputs/${reproduction.offload_profile}/b40/checkpoints
